spring:
  application:
    name: communication_manager
  profiles:
    active:
      - dev
      - no-security
      - api-docs
  config:
    import:
      - optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: producer
      properties:
        max.request.size: ${KAFKA_PRODUCER_MAX_REQUEST_SIZE:10485760}
        message.max.bytes: ${KAFKA_PRODUCER_MESSAGE_MAX_BYTES:10485760}

camel:
  component:
    google-mail-stream:
      application-name: ${gmail.application-name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

    google-mail:
      application-name: ${gmail.application-name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

kafka-config:
  attachment-topic: ${ATTACHMENT_TOPIC:attachment.json}
  mail-topic: ${MAIL_TOPIC:mail.json}

server:
  port: ${PORT:8080}

openapi:
  base-url: ${OPENAPI_BASE_URL:http://localhost:${server.port}}
