name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Releasing
        uses: ncipollo/release-action@v1
        # Documentation can be found at https://github.com/ncipollo/release-action
        working-directory: ./communication_manager
        with:
          generateReleaseNotes: true
          bodyFile: "DOCKER.md"

